### ISSUE TITLE
Bounce email renders incorrectly

### ISSUE THREAD

**Issue by djensen47** [akhoury/nodebb-plugin-emailer-mandrill#19]
The bounce email is being rendered as follows:

> Hello,

> bounce.generic

I do have the default language on my forums set to en_US

**Comment by julianlam** [comment]
Can you let me know the version of NodeBB you're running?

**Comment by djensen47** [comment]
0.9.3

**Comment by julianlam** [comment]
Fixed in v0.3.5

**Comment by djensen47** [comment]
I'm still seeing the issue. Is there something that I need to do?

**Comment by julianlam** [comment]
After updating the plugin, you'll need to execute a full restart of NodeBB.

**Comment by djensen47** [comment]
I've done that. :confused: 

I did it again but I still see the same email response.

**Comment by djensen47** [comment]
I tried creating a new topic, got a new email notification, and responded with an unregistered email address and I'm still getting the following:

> Hello,
>
> bounce.generic

I would re-open the issue but it appears that I cannot.

**Comment by julianlam** [comment]
Odd, what is your setup again? Can you output the contents of `plugin.json` for this module?

**Comment by djensen47** [comment]
NodeBB 0.9.3 using MongoDB. I've set the default language of the forums to en_US.

`plugin.json`
```json
{
    "id": "nodebb-plugin-emailer-mandrill",
    "name": "Emailer (Mandrill)",
    "description": "Mandrill Emailer for NodeBB",
    "url": "https://github.com/akhoury/nodebb-plugin-emailer-mandrill",
    "library": "./index.js",
    "templates": "templates",
    "hooks": [
        { "hook": "filter:email.send", "method": "send"},
        { "hook": "filter:admin.header.build", "method": "admin.menu"},
        { "hook": "static:app.load", "method": "init" }
    ],
    "languages": "languages",
    "defaultLang": "en_GB"
}
```

The plugin admin page shows that I am indeed running version 0.3.5 of the emailer-mandrill plugin.

**Comment by julianlam** [comment]
How did you restart? Perhaps try a full stop of NodeBB and start...

**Comment by djensen47** [comment]
From yesterday …

> I've done that. :confused:
>
> I restarted again but I still see the same email response.

 I have done a complete restart several times. I've also started in both developer mode and regular.

**Comment by djensen47** [comment]
It looks like it is a bug in NodeBB.

In the ACP > General > Language I changed _from_ en_US _to_ en_GB and it started working. The defaultLang setting appears to no be working?

**Comment by djensen47** [comment]
Should I file an issue against NodeBB?
